package com.expensetracker.sms.parser

import com.expensetracker.domain.model.TransactionType

/**
 * Internet-sourced Indian bank/UPI/card SMS audit corpus, anonymized and shaped
 * from public DLT-style examples and open parser documentation samples.
 */
object InternetSmsCorpus {

    data class Case(
        val id: String,
        val sender: String,
        val body: String,
        val expect: Expect,
    )

    data class Expect(
        val keep: Boolean,
        val type: TransactionType? = null,
        val category: String? = null,
        val amount: String? = null,
        val merchantContains: String? = null,
        val spend: Boolean? = null,
        val notes: String,
    )

    val cases: List<Case> = listOf(
        Case(
            id = "keep-hdfc-upi-amazon-001",
            sender = "VM-HDFCBK",
            body = "Rs 245.00 debited from A/c XXXX1234 on 12-01-24 at AMAZON via UPI. Bal: Rs 12,340.55. UPI Ref 401234567890",
            expect = Expect(true, TransactionType.DEBIT, Categories.SHOPPING, "245.00", "Amazon", true, "HDFC UPI debit to known shopping merchant."),
        ),
        Case(
            id = "keep-hdfc-upi-zomato-002",
            sender = "VM-HDFCBK",
            body = "Rs.1,763.00 debited from A/c XX1234 on 09-Aug-26 for UPI/503547865861-ZOMATO. Avl Bal Rs 8,201.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.FOOD, "1763.00", "Zomato", true, "HDFC UPI merchant debit should be Food."),
        ),
        Case(
            id = "keep-hdfc-upi-swiggy-003",
            sender = "AD-HDFCBK",
            body = "Rs 420.00 debited from A/c XX1234 on 02-Aug-26 at SWIGGY via UPI. UPI Ref 8001001. Avl Bal Rs 19,580.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.FOOD, "420.00", "Swiggy", true, "Known food merchant spend."),
        ),
        Case(
            id = "keep-hdfc-upi-bigbasket-004",
            sender = "VM-HDFCBK",
            body = "Rs.450.00 debited from A/c XX1234 on 15-APR for UPI/412839-BIGBASKET. Avl Bal Rs 8,200.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.GROCERIES, "450.00", "BigBasket", true, "Quick grocery merchant should map to Groceries."),
        ),
        Case(
            id = "keep-hdfc-card-netflix-005",
            sender = "VD-HDFCBK",
            body = "HDFC Bank: You spent Rs. 649.00 at NETFLIX on Credit Card XX1234 on 08-08-26. Avl Limit Rs 92,140.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.SUBSCRIPTION, "649.00", "Netflix", true, "Subscription card spend."),
        ),
        Case(
            id = "keep-hdfc-upi-airtel-006",
            sender = "VM-HDFCBK",
            body = "Rs 153.81 debited from A/c XX1234 on 09-Aug-26 for UPI/543001850491-AIRTEL. Avl Bal Rs 8,047.19",
            expect = Expect(true, TransactionType.DEBIT, Categories.RECHARGE, "153.81", "Airtel", true, "Airtel recharge debit."),
        ),
        Case(
            id = "keep-hdfc-card-fuel-007",
            sender = "VM-HDFCBK",
            body = "Alert: You've spent INR 2,000.00 on your HDFC Bank Card **9123 at INDIAN OIL on 05/08/2026 at 11:07 IST.",
            expect = Expect(true, TransactionType.DEBIT, Categories.FUEL, "2000.00", "Indian Oil", true, "Fuel card spend."),
        ),
        Case(
            id = "keep-hdfc-upi-uber-008",
            sender = "AD-HDFCBK",
            body = "Rs 386.40 debited from A/c XX1234 on 06-Aug-26 at UBER via UPI. UPI Ref 611122233344. Avl Bal Rs 17,200.50",
            expect = Expect(true, TransactionType.DEBIT, Categories.TRANSPORT, "386.40", "Uber", true, "Cab merchant spend."),
        ),
        Case(
            id = "keep-hdfc-neft-salary-009",
            sender = "VM-HDFCBK",
            body = "INR 75000.00 credited to A/c XXXX9876 on 01-Aug-26 by NEFT from ACME CORP SALARY. Avl Bal Rs 1,20,450.00 Ref N001234",
            expect = Expect(true, TransactionType.CREDIT, Categories.SALARY, "75000.00", null, false, "Salary credit is income, not spend."),
        ),
        Case(
            id = "keep-hdfc-refund-amazon-010",
            sender = "VM-HDFCBK",
            body = "Rs 1,499.00 has been credited to your HDFC Bank A/c XX1234 as refund from AMAZON on 09-08-26. Ref 900123456.",
            expect = Expect(true, TransactionType.CREDIT, Categories.REFUND, "1499.00", "Amazon", false, "Refund offsets spend, not income."),
        ),
        Case(
            id = "keep-hdfc-credit-card-payment-transfer-011",
            sender = "VM-HDFCBK",
            body = "Rs 3,200.00 debited from A/c XX1234 for payment to Credit Card XX1014 via NetBanking on 09-08-26.",
            expect = Expect(true, TransactionType.DEBIT, Categories.TRANSFER, "3200.00", null, false, "Bank-side card bill debit is a transfer."),
        ),
        Case(
            id = "keep-hdfc-groww-investment-012",
            sender = "VM-HDFCBK",
            body = "Rs 5,000.00 debited from A/c XX4411 for GROWW purchase on 02-07-24. UPI Ref 512345678901. Avl Bal Rs 22,100.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.INVESTMENT, "5000.00", "Groww", false, "Groww purchase is Investment."),
        ),
        Case(
            id = "keep-sbi-neft-salary-013",
            sender = "VM-SBIINB",
            body = "INR 50000.00 credited to A/c XXXX9876 on 01-Feb-24 by NEFT from Acme Corp Salary. Avl Bal Rs 1,20,450.00 Ref N001234",
            expect = Expect(true, TransactionType.CREDIT, Categories.SALARY, "50000.00", null, false, "SBI salary credit."),
        ),
        Case(
            id = "keep-sbi-atm-cash-014",
            sender = "JD-SBIINB",
            body = "Dear SBI Customer, your A/c XX9876 has been debited by Rs. 4,000.00 on 07-Aug-26 for ATM CASH WDL. Avl Bal Rs 21,000.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.CASH_WITHDRAWAL, "4000.00", null, true, "ATM withdrawal is cash spend bucket."),
        ),
        Case(
            id = "keep-sbi-upi-zomato-015",
            sender = "VM-SBIINB",
            body = "A/c XX9876 debited by INR 350.00 on 08-Aug-26 to ZOMATO via UPI Ref 812345678901. Avl Bal INR 19,650.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.FOOD, "350.00", "Zomato", true, "SBI UPI food debit."),
        ),
        Case(
            id = "keep-sbi-imps-owner-transfer-016",
            sender = "VM-SBIINB",
            body = "A/c XX9876 debited by Rs. 15,000.00 on 05-Aug-26 via IMPS to ANUR Ref IMPS621706928597. Avl Bal Rs 44,996.19",
            expect = Expect(true, TransactionType.DEBIT, Categories.TRANSFER, "15000.00", null, false, "Owner-name IMPS is self transfer."),
        ),
        Case(
            id = "keep-sbi-refund-flipkart-017",
            sender = "AX-SBIINB",
            body = "Your SBI A/c XX9876 has been credited with Rs.799.00 as refund from FLIPKART on 06-Aug-26. Ref 900654321.",
            expect = Expect(true, TransactionType.CREDIT, Categories.REFUND, "799.00", "Flipkart", false, "Merchant refund should be Refund."),
        ),
        Case(
            id = "keep-sbi-neft-rent-018",
            sender = "VM-SBIINB",
            body = "A/c XX9876 debited by INR 22000.00 on 03-Aug-26 for NEFT RENT to landlord Ref N246813579. Avl Bal INR 60,000.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.RENT, "22000.00", null, true, "Rent debit should be spend."),
        ),
        Case(
            id = "keep-sbi-card-amazon-019",
            sender = "AD-SBICRD",
            body = "Your SBI Credit Card ending 4321 has been used for Rs 2,450.00 at AMAZON on 05-Aug-26. Avl limit Rs 46,251.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.SHOPPING, "2450.00", "Amazon", true, "SBI card shopping spend."),
        ),
        Case(
            id = "keep-icici-info-upi-swiggy-020",
            sender = "AX-ICICIB",
            body = "Dear Customer, your ICICI Bank A/c XX789 has been debited with Rs 499.00 on 03/03/24. Info: UPI/408123/SWIGGY. Bal: Rs 5,231.10",
            expect = Expect(true, TransactionType.DEBIT, Categories.FOOD, "499.00", "Swiggy", true, "ICICI Info UPI merchant spend."),
        ),
        Case(
            id = "keep-icici-card-avenue-021",
            sender = "AD-ICICIT",
            body = "Rs 8,646.47 spent on ICICI Bank Card XX1014 on 26-Jul-26 at Avenue Supermar. Avl Lmt: Rs 2,06,758.37. To convert this txn to EMI give a missed call on 9924667667.",
            expect = Expect(true, TransactionType.DEBIT, Categories.GROCERIES, "8646.47", "DMart", true, "Avenue Supermar card spend is groceries, EMI footer ignored."),
        ),
        Case(
            id = "keep-icici-upi-apollo-022",
            sender = "AX-ICICIB",
            body = "ICICI Bank Acct XX293 debited for Rs 600.07 on 25-Jul-26; Apollo Pharmacy credited. UPI:657221332249. Call 18002662 for dispute.",
            expect = Expect(true, TransactionType.DEBIT, Categories.MEDICAL, "600.07", "Apollo", true, "Known merchant in '; credited' template is spend."),
        ),
        Case(
            id = "keep-icici-upi-motilal-023",
            sender = "AX-ICICIB",
            body = "ICICI Bank Acct XX293 debited for Rs 40000.00 on 03-Aug-26; MotilalOswalMF credited. UPI:479986606620.",
            expect = Expect(true, TransactionType.DEBIT, Categories.INVESTMENT, "40000.00", "Motilal", false, "MotilalOswalMF is Investment."),
        ),
        Case(
            id = "keep-icici-atd-card-autodebit-024",
            sender = "AD-ICICIT",
            body = "ICICI Bank Acc XX293 debited Rs. 29,004.46 on 02-Jun-26 InfoATD*Auto Debi.Avl Bal Rs. 3,12,078.24.",
            expect = Expect(true, TransactionType.DEBIT, Categories.TRANSFER, "29004.46", null, false, "Bank-side card auto-debit is Transfer."),
        ),
        Case(
            id = "keep-icici-bil-neft-transfer-025",
            sender = "AX-ICICIB",
            body = "ICICI Bank Acc XX293 debited Rs. 10,000.00 on 08-Aug-26 InfoBIL*NEFT*IN12618244087080.Avl Bal Rs. 85,321.00.",
            expect = Expect(true, TransactionType.DEBIT, Categories.TRANSFER, "10000.00", null, false, "InfoBIL NEFT is account transfer."),
        ),
        Case(
            id = "keep-icici-ach-racpc-emi-026",
            sender = "AX-ICICIB",
            body = "ICICI Bank Acc XX293 debited Rs. 24,911.00 on 05-Aug-26 InfoACH*RACPC CUM.Avl Bal Rs. 6,52,083.87.",
            expect = Expect(true, TransactionType.DEBIT, Categories.EMI, "24911.00", null, true, "RACPC ACH collect is loan EMI."),
        ),
        Case(
            id = "keep-icici-card-amazon-027",
            sender = "AD-ICICIT",
            body = "ICICI Bank Credit Card XX1014 is used for Rs 2,450.00 at AMAZON on 05-Aug-26. Avl limit Rs 46,251.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.SHOPPING, "2450.00", "Amazon", true, "ICICI card used-for shopping."),
        ),
        Case(
            id = "keep-icici-card-netflix-028",
            sender = "AD-ICICIT",
            body = "Dear Customer, your ICICI Bank Credit Card XX1014 has been used for a transaction of Rs 649.00 on 01-Aug-26 at NETFLIX. Avl limit Rs 48,701.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.SUBSCRIPTION, "649.00", "Netflix", true, "Netflix subscription card spend."),
        ),
        Case(
            id = "keep-icici-card-airtel-029",
            sender = "CP-ICICIT",
            body = "ICICI Bank Credit Card XX7002 debited for INR 153.81 on 09-Aug-26 for UPI-543001850491-Airtel. To dispute call 18001080.",
            expect = Expect(true, TransactionType.DEBIT, Categories.RECHARGE, "153.81", "Airtel", true, "Airtel UPI-card recharge."),
        ),
        Case(
            id = "keep-icici-dmart-card-030",
            sender = "AD-ICICIT",
            body = "Thank you for using your ICICI Bank Credit Card XX1014 for INR 1,980.00 at DMART on 04-Aug-26. Avl limit Rs 44,271.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.GROCERIES, "1980.00", "DMart", true, "DMart groceries card spend."),
        ),
        Case(
            id = "keep-icici-refund-myntra-031",
            sender = "AX-ICICIB",
            body = "Your transaction of Rs 799.00 on ICICI Bank Credit Card XX1014 at MYNTRA has been reversed. Ref 900654321.",
            expect = Expect(true, TransactionType.CREDIT, Categories.REFUND, "799.00", "Myntra", false, "Reversal without credited is Refund."),
        ),
        Case(
            id = "keep-icici-salary-credit-032",
            sender = "AX-ICICIB",
            body = "ICICI Bank Account XX293 credited with INR 98000.00 on 31-Jul-26 by NEFT SALARY ACME INDIA Ref SAL987654.",
            expect = Expect(true, TransactionType.CREDIT, Categories.SALARY, "98000.00", null, false, "ICICI salary credit."),
        ),
        Case(
            id = "keep-icici-unknown-person-credited-transfer-033",
            sender = "AX-ICICIB",
            body = "ICICI Bank Acct XX293 debited for Rs 2,500.00 on 08-Aug-26; LALAWMPUII credited. UPI:111991242206.",
            expect = Expect(true, TransactionType.DEBIT, Categories.TRANSFER, "2500.00", null, false, "Unknown person credited in ICICI UPI is Transfer intent."),
        ),
        Case(
            id = "keep-icici-owner-upi-transfer-034",
            sender = "AX-ICICIB",
            body = "ICICI Bank Acct XX293 debited for Rs 100000.00 on 01-Aug-26; ANURAG SINGH credited. UPI:781919319954.",
            expect = Expect(true, TransactionType.DEBIT, Categories.TRANSFER, "100000.00", null, false, "Owner-name UPI is self transfer."),
        ),
        Case(
            id = "keep-icici-upi-1mg-035",
            sender = "AX-ICICIB",
            body = "ICICI Bank Acct XX293 debited for Rs 1,150.00 on 06-Aug-26; TATA 1MG credited. UPI:657221332250.",
            expect = Expect(true, TransactionType.DEBIT, Categories.MEDICAL, "1150.00", "1mg", true, "1mg is medical spend."),
        ),
        Case(
            id = "keep-icici-irctc-travel-036",
            sender = "AD-ICICIB",
            body = "ICICI Bank A/c XX293 has been debited with Rs 1,850.00 on 07-Aug-26. Info: UPI/912345/IRCTC. Bal Rs 70,000.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.TRAVEL, "1850.00", "IRCTC", true, "IRCTC travel spend."),
        ),
        Case(
            id = "keep-icici-jio-recharge-037",
            sender = "AD-ICICIT",
            body = "Thank you for using ICICI Bank Credit Card XX1014 for Rs 555.00 at BD JIO MONEY on 05-Aug-26.",
            expect = Expect(true, TransactionType.DEBIT, Categories.RECHARGE, "555.00", "Jio", true, "Jio Money recharge spend."),
        ),
        Case(
            id = "keep-icici-insurance-premium-038",
            sender = "AX-ICICIB",
            body = "ICICI Bank Acc XX293 debited Rs. 12,340.00 on 10-Aug-26 InfoINSURANCE PREMIUM PAID.Avl Bal Rs. 80,100.00.",
            expect = Expect(true, TransactionType.DEBIT, Categories.INSURANCE, "12340.00", null, true, "Insurance premium is spend."),
        ),
        Case(
            id = "keep-axis-neft-transfer-039",
            sender = "VM-AXISBK",
            body = "Debit INR 17383.00\nAxis Bank A/c XX8291\n15-06-26 20:43:26\nNEFT/MB/AXOMB16602145999/V\nWhatsApp BAL to 917036165000",
            expect = Expect(true, TransactionType.DEBIT, Categories.TRANSFER, "17383.00", null, false, "Axis compact NEFT is Transfer."),
        ),
        Case(
            id = "keep-axis-salary-credit-040",
            sender = "VM-AXISBK",
            body = "Credit INR 92000.00\nAxis Bank A/c XX8291\n01-08-26 09:10:05\nNEFT/SALARY/ACME INDIA/AXIS987654321",
            expect = Expect(true, TransactionType.CREDIT, Categories.SALARY, "92000.00", null, false, "Axis salary credit."),
        ),
        Case(
            id = "keep-axis-upi-p2a-person-041",
            sender = "VM-AXISBK",
            body = "INR 2500.00 debited\nA/c no. XX8291\n08-08-26, 14:46:26\nUPI/P2A/111991242206/LALAWMPUII\nAxis Bank",
            expect = Expect(true, TransactionType.DEBIT, Categories.OTHERS, "2500.00", "LALAWMPUII", true, "Unknown person P2A is uncategorized spend in current parser intent."),
        ),
        Case(
            id = "keep-axis-upi-p2m-person-042",
            sender = "VM-AXISBK",
            body = "INR 60.00 debited\nA/c no. XX8291\n09-08-26, 07:11:03\nUPI/P2M/273322632216/ANIL KUMAR RAM\nAxis Bank",
            expect = Expect(true, TransactionType.DEBIT, Categories.OTHERS, "60.00", "ANIL", true, "Unknown small P2M merchant remains Others spend."),
        ),
        Case(
            id = "keep-axis-card-flipkart-043",
            sender = "VM-AXISBK",
            body = "Thank you for using AXIS Bank Credit Card ending 4321 for Rs. 1,299.00 on FLIPKART on 15-04-24. Avl limit Rs 48,701.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.SHOPPING, "1299.00", "Flipkart", true, "Axis card shopping."),
        ),
        Case(
            id = "keep-axis-ach-hdfc-emi-044",
            sender = "VM-AXISBK",
            body = "Debit INR 27136.00\nAxis Bank A/c XX8291\n05-08-26 09:40:02\nACH-DR-HDFC BANK LTD-47138\nWhatsApp BAL to 917036165000",
            expect = Expect(true, TransactionType.DEBIT, Categories.EMI, "27136.00", "HDFC Bank", true, "ACH-DR HDFC Bank is EMI."),
        ),
        Case(
            id = "keep-axis-ach-scripbox-investment-045",
            sender = "VM-AXISBK",
            body = "Debit INR 1300.00\nAxis Bank A/c XX8291\n01-08-26 08:19:18\nACH-DR-SCRIPBOXWEALTHMANAG\nWhatsApp BAL to 917036165000",
            expect = Expect(true, TransactionType.DEBIT, Categories.INVESTMENT, "1300.00", "Scripbox", false, "ACH-DR Scripbox is Investment."),
        ),
        Case(
            id = "keep-axis-nach-scripbox-046",
            sender = "VM-AXISBK",
            body = "NACH debit towards SCRIPBOXWEALTHMANAGE for INR 1,300.00 with UMRN UTIB7010806200000399 has been successfully processed in A/c no. XX8291 today - Axis Bank",
            expect = Expect(true, TransactionType.DEBIT, Categories.INVESTMENT, "1300.00", "Scripbox", false, "NACH Scripbox is Investment."),
        ),
        Case(
            id = "keep-axis-nach-groww-047",
            sender = "VM-AXISBK",
            body = "NACH debit towards GROWW PAY SERVICES for INR 5,000.00 with UMRN UTIB7010806200000400 has been successfully processed in A/c no. XX8291 today - Axis Bank",
            expect = Expect(true, TransactionType.DEBIT, Categories.INVESTMENT, "5000.00", "Groww", false, "NACH Groww is Investment."),
        ),
        Case(
            id = "keep-axis-nach-hdfc-emi-048",
            sender = "VM-AXISBK",
            body = "NACH debit towards HDFC BANK LTD for INR 27,136.00 with UMRN UTIB7022807210000967 has been successfully processed in A/c no. XX8291 today - Axis Bank",
            expect = Expect(true, TransactionType.DEBIT, Categories.EMI, "27136.00", "HDFC Bank", true, "NACH HDFC Bank loan collect is EMI."),
        ),
        Case(
            id = "keep-axis-idfc-credit-transfer-049",
            sender = "VM-AXISBK",
            body = "Credit INR 15000.00\nAxis Bank A/c XX8291\n05-08-26 06:44:55\nIMPS/P2A/621706928597/ANUR",
            expect = Expect(true, TransactionType.CREDIT, Categories.TRANSFER, "15000.00", null, false, "Owner-name IMPS credit is Transfer."),
        ),
        Case(
            id = "keep-axis-card-starbucks-050",
            sender = "VM-AXISBK",
            body = "Spent INR 420.00 on Axis Bank Credit Card XX4321 at STARBUCKS on 06-Aug-26. Avl limit INR 49,580.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.FOOD, "420.00", "Starbucks", true, "Coffee card spend is Food."),
        ),
        Case(
            id = "keep-axis-upi-zepto-051",
            sender = "VM-AXISBK",
            body = "INR 349.00 debited\nA/c no. XX8291\n04-08-26, 18:11:03\nUPI/P2M/712345678901/ZEPTO\nAxis Bank",
            expect = Expect(true, TransactionType.DEBIT, Categories.GROCERIES, "349.00", "Zepto", true, "Zepto quick commerce groceries."),
        ),
        Case(
            id = "keep-axis-upi-netflix-052",
            sender = "VM-AXISBK",
            body = "INR 649.00 debited\nA/c no. XX8291\n01-08-26, 10:11:03\nUPI/P2M/812345678901/NETFLIX\nAxis Bank",
            expect = Expect(true, TransactionType.DEBIT, Categories.SUBSCRIPTION, "649.00", "Netflix", true, "Netflix UPI subscription."),
        ),
        Case(
            id = "keep-axis-card-payment-transfer-053",
            sender = "VM-AXISBK",
            body = "Debit INR 3868.40\nAxis Bank A/c XX8291\n02-07-26 10:41:54\nCRD-PMNT-530562****0887\nWhatsApp BAL to 917036165000",
            expect = Expect(true, TransactionType.DEBIT, Categories.TRANSFER, "3868.40", null, false, "Axis CRD-PMNT is card bill transfer."),
        ),
        Case(
            id = "keep-axis-cash-withdrawal-054",
            sender = "VM-AXISBK",
            body = "Debit INR 5000.00\nAxis Bank A/c XX8291\n07-08-26 16:20:02\nATM CASH WDL 1234 BENGALURU\nAvl Bal INR 30,100.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.CASH_WITHDRAWAL, "5000.00", null, true, "Axis ATM withdrawal."),
        ),
        Case(
            id = "keep-axis-refund-amazon-055",
            sender = "VM-AXISBK",
            body = "Credit INR 899.00\nAxis Bank A/c XX8291\n06-08-26 10:31:02\nREFUND FROM AMAZON Ref 998877665544",
            expect = Expect(true, TransactionType.CREDIT, Categories.REFUND, "899.00", "Amazon", false, "Axis refund credit."),
        ),
        Case(
            id = "keep-axis-fuel-bpcl-056",
            sender = "VM-AXISBK",
            body = "Spent INR 2,500.00 on Axis Bank Debit Card XX4321 at BPCL FUEL STATION on 08-Aug-26.",
            expect = Expect(true, TransactionType.DEBIT, Categories.FUEL, "2500.00", "Bharat", true, "BPCL fuel spend."),
        ),
        Case(
            id = "keep-axis-bookmyshow-057",
            sender = "VM-AXISBK",
            body = "Spent INR 760.00 on Axis Bank Credit Card XX4321 at BOOKMYSHOW on 08-Aug-26.",
            expect = Expect(true, TransactionType.DEBIT, Categories.ENTERTAINMENT, "760.00", "BookMyShow", true, "Movie ticket spend."),
        ),
        Case(
            id = "keep-kotak-fastag-058",
            sender = "AD-KOTAKB",
            body = "Rs 500 debited for FASTag recharge on 20-05-24 from A/c XX2222. Ref 501234567. Avl Bal Rs 1234.56",
            expect = Expect(true, TransactionType.DEBIT, Categories.TRANSPORT, "500.00", "FASTag", true, "FASTag is transport spend."),
        ),
        Case(
            id = "keep-idfc-received-upi-059",
            sender = "JM-IDFCBK",
            body = "Rs 1,000.00 received in your IDFC FIRST Bank Account XX293 from anurag singh-1@okicici on 07-08-26. UPI: 807123456789",
            expect = Expect(true, TransactionType.CREDIT, Categories.TRANSFER, "1000.00", null, false, "IDFC received UPI is Transfer credit."),
        ),
        Case(
            id = "keep-idfc-salary-060",
            sender = "JM-IDFCBK",
            body = "INR 110000.00 credited to your IDFC FIRST Bank Account XX293 via NEFT SALARY from EXAMPLE TECH PVT LTD on 31-Jul-26.",
            expect = Expect(true, TransactionType.CREDIT, Categories.SALARY, "110000.00", null, false, "IDFC salary credit."),
        ),
        Case(
            id = "keep-idbi-ppf-si-061",
            sender = "VM-IDBIBK",
            body = "SI Transaction of Rs 12000 successfully credited in PPF Ac No ****************0079 on 07/08/2026 -IDBI Bank",
            expect = Expect(true, TransactionType.DEBIT, Categories.INVESTMENT, "12000.00", "PPF", false, "PPF SI is Investment debit."),
        ),
        Case(
            id = "keep-kotak-dmart-062",
            sender = "AD-KOTAKB",
            body = "Your Kotak Bank A/c XX2222 is debited by Rs. 2,150.00 at DMART via UPI on 08-Aug-26. UPI Ref 456789123456.",
            expect = Expect(true, TransactionType.DEBIT, Categories.GROCERIES, "2150.00", "DMart", true, "Kotak DMart groceries."),
        ),
        Case(
            id = "keep-yesbank-refund-063",
            sender = "VM-YESBNK",
            body = "Your YES BANK A/c XX4567 has been credited with INR 1,250.00 REFUND from MYNTRA on 08-Aug-26. UTR YES123456789.",
            expect = Expect(true, TransactionType.CREDIT, Categories.REFUND, "1250.00", "Myntra", false, "Refund from known merchant."),
        ),
        Case(
            id = "keep-canara-salary-064",
            sender = "VM-CANBNK",
            body = "Canara Bank A/c XX9988 credited with Rs. 68000.00 by NEFT SALARY from ACME SERVICES on 01-Aug-26. Avl Bal Rs. 90,000.00",
            expect = Expect(true, TransactionType.CREDIT, Categories.SALARY, "68000.00", null, false, "Canara salary credit."),
        ),
        Case(
            id = "keep-federal-insurance-065",
            sender = "VM-FEDBNK",
            body = "Federal Bank A/c XX4455 debited with Rs 9,876.00 for INSURANCE PREMIUM PAID on 10-Aug-26. Avl Bal Rs 40,000.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.INSURANCE, "9876.00", null, true, "Insurance premium debit."),
        ),
        Case(
            id = "ignore-otp-hdfc-066",
            sender = "VM-HDFCBK",
            body = "123456 is your OTP for HDFC Bank net banking login. Do not share with anyone.",
            expect = Expect(false, notes = "OTP is not a ledger event."),
        ),
        Case(
            id = "ignore-otp-icici-067",
            sender = "AX-ICICIB",
            body = "ICICI Bank OTP 882211 for transaction of Rs 499.00 at SWIGGY. Do not share OTP with anyone.",
            expect = Expect(false, notes = "Authorization OTP before payment is ignored."),
        ),
        Case(
            id = "ignore-otp-upi-068",
            sender = "VM-SBIINB",
            body = "Your UPI verification code is 445566 for BHIM SBI Pay. Amount Rs 1.00 may be shown for validation only.",
            expect = Expect(false, notes = "UPI verification code is not movement."),
        ),
        Case(
            id = "ignore-emi-scheduled-069",
            sender = "VM-HDFCBK",
            body = "Dear customer, your EMI of Rs. 99650.00 is scheduled for ECS clearance on 10-08-2026. Please keep sufficient balance.",
            expect = Expect(false, notes = "Future scheduled EMI notice should be ignored."),
        ),
        Case(
            id = "ignore-will-be-debited-070",
            sender = "AD-ICICIT",
            body = "Total Amount of INR 34,757.45 is due on ICICI Bank Credit Card XX1014. Amount will be debited from Savings Account XX293 on 02-Aug-26. Please ignore if paid.",
            expect = Expect(false, notes = "Future auto-debit due notice is not completed movement."),
        ),
        Case(
            id = "ignore-card-payment-received-071",
            sender = "AD-SBICRD",
            body = "SBI Card: Payment of INR 10,000 received against your Credit Card XX1234 on 2026-08-12.",
            expect = Expect(false, notes = "Card issuer payment ack duplicates bank debit."),
        ),
        Case(
            id = "ignore-card-thank-you-payment-072",
            sender = "AD-ICICIT",
            body = "Dear Customer, thank you for your payment of INR 29,004.46 towards ICICI Bank Credit Card Account XX4104 through Auto Debit from Account XX6293 on 02-Jun-26",
            expect = Expect(false, notes = "Thank-you card payment confirmation is ignored."),
        ),
        Case(
            id = "ignore-card-credited-073",
            sender = "VM-AXISBK",
            body = "Dear cardmember, Payment of Rs 2487 was credited to your card ending 1234 on 05/Aug/2026.",
            expect = Expect(false, notes = "Credit to card is card-side ack."),
        ),
        Case(
            id = "ignore-neft-beneficiary-074",
            sender = "VM-AXISBK",
            body = "Your NEFT txn with Ref. No. AXOMB22002006227 for INR 10000.00 is credited to beneficiary Manju Singh, A/c no. XX5116 on 08-08-26 at 11:52:35 IST - Axis Bank",
            expect = Expect(false, notes = "Beneficiary delivery ack is not source-account movement."),
        ),
        Case(
            id = "ignore-nach-returned-075",
            sender = "VM-AXISBK",
            body = "NACH debit towards SCRIPBOXWEALTHMANAGE for INR 1,300.00 with UMRN UTIB7010806200000399 has been returned today in A/c no. XX8291 - Axis Bank",
            expect = Expect(false, notes = "Returned NACH means no completed debit."),
        ),
        Case(
            id = "ignore-scripbox-withdrawal-processed-076",
            sender = "VM-SCRPBX",
            body = "Your withdrawal instruction of Rs 52036.55 has been successfully processed.-Team Scripbox",
            expect = Expect(false, notes = "Broker withdrawal status is not bank credit."),
        ),
        Case(
            id = "ignore-scripbox-withdrawal-request-077",
            sender = "VM-SCRPBX",
            body = "You have placed a withdrawal request for Rs 51179.97 on Aug 3, 2026.-Team Scripbox",
            expect = Expect(false, notes = "Withdrawal request is not movement."),
        ),
        Case(
            id = "ignore-iprumf-sip-purchase-078",
            sender = "VM-IPRUMF",
            body = "Dear Investor, Your SIP Purchase of Rs.2,799.86 in Folio 44796240 in Large Cap Fund - Growth for 25.154 units has been processed for NAV of Rs.111.31 on 03-Aug-2026 - IPRUMF",
            expect = Expect(false, notes = "AMC SIP confirmation duplicates bank NACH."),
        ),
        Case(
            id = "ignore-doodhvale-payment-079",
            sender = "VM-DOODHV",
            body = "Dear Customer, we have received online payment of Rs. 1000 .Thank you. Doodhvale.com",
            expect = Expect(false, notes = "Merchant online payment ack is ignored."),
        ),
        Case(
            id = "ignore-cashback-promo-080",
            sender = "AX-PROMO",
            body = "Get up to Rs 500 cashback on UPI spends this weekend. Shop now. T&C apply.",
            expect = Expect(false, notes = "Cashback offer is marketing."),
        ),
        Case(
            id = "ignore-loan-offer-081",
            sender = "VM-HDFCBK",
            body = "Congratulations! Pre-approved loan offer of Rs 2,00,000. Apply now for instant approval.",
            expect = Expect(false, notes = "Loan offer is not ledger movement."),
        ),
        Case(
            id = "ignore-credit-limit-raise-082",
            sender = "CP-ICICIT",
            body = "Manage spends effectively by increasing the limit on ICICI Bank Credit Card XX1014 from Rs300000 to Rs1000000. SMS CRLIM 1014 to 5676766 to raise the limit",
            expect = Expect(false, notes = "Credit-limit marketing should not parse."),
        ),
        Case(
            id = "ignore-balance-only-083",
            sender = "VM-HDFCBK",
            body = "Your A/c XX1234 Avl Bal Rs 12,340.55 as on 12-01-24. Do not share OTP with anyone.",
            expect = Expect(false, notes = "Balance-only alert is ignored."),
        ),
        Case(
            id = "ignore-autopay-activated-084",
            sender = "AD-ICICIT",
            body = "Auto Pay is activated for ICICI Bank Credit Card XX1014. INR 1,631.00 will be debited from Account XX293 on due date.",
            expect = Expect(false, notes = "Auto-pay setup notice is not debit."),
        ),
        Case(
            id = "ignore-emi-marketing-085",
            sender = "VM-HDFCBK",
            body = "No cost EMI starting Rs 999 on purchases above Rs 5000 on your HDFC Bank Credit Card. Limited period offer.",
            expect = Expect(false, notes = "EMI marketing alone is ignored."),
        ),
        Case(
            id = "ignore-statement-ready-086",
            sender = "AD-SBICRD",
            body = "Your SBI Card statement is ready. Total amount due Rs 12,340.00, due date 20-Aug-26. Please ignore if already paid.",
            expect = Expect(false, notes = "Statement/due notice is not movement."),
        ),
        Case(
            id = "ignore-bill-generated-087",
            sender = "VM-AIRTEL",
            body = "Your Airtel bill is generated for Rs 899.00. Pay before 18-Aug-26 to avoid late fee.",
            expect = Expect(false, notes = "Bill generated notice is ignored."),
        ),
        Case(
            id = "ignore-reward-expiry-088",
            sender = "VM-HDFCBK",
            body = "Your 1250 reward points will expire soon. Redeem vouchers worth Rs 500 on SmartBuy. T&C apply.",
            expect = Expect(false, notes = "Reward points promo is ignored."),
        ),
        Case(
            id = "ignore-kyc-update-089",
            sender = "AD-KOTAKB",
            body = "KYC update required for your Kotak account. Complete your KYC to continue transactions up to Rs 100000.",
            expect = Expect(false, notes = "KYC service notice is not movement."),
        ),
        Case(
            id = "ignore-payment-received-success-090",
            sender = "VM-BILLDK",
            body = "Payment of Rs 899.00 received successfully for your electricity bill. Ref BBPS123456.",
            expect = Expect(false, notes = "Biller payment ack duplicates bank debit."),
        ),
        Case(
            id = "ignore-merchant-received-card-091",
            sender = "AD-FLIPKT",
            body = "We have received payment from credit card ending 4321 for Rs 1,299.00 at FLIPKART on 15-04-24. Order confirmed.",
            expect = Expect(false, notes = "Merchant card payment ack is ignored."),
        ),
        Case(
            id = "ignore-ppf-contribution-092",
            sender = "VM-IDBIBK",
            body = "ICICI Bank: Amount of INR 10,000 received in your PPF account XX9988 contribution. Thank you.",
            expect = Expect(false, notes = "PPF contribution thank-you is not source debit."),
        ),
        Case(
            id = "ignore-nps-contribution-093",
            sender = "VM-CRA",
            body = "We have received your contribution of Rs 5,000 towards NPS Tier I. Thank you.",
            expect = Expect(false, notes = "NPS contribution acknowledgement is ignored."),
        ),
        Case(
            id = "ignore-etmoney-refund-initiated-094",
            sender = "VM-ETMONEY",
            body = "Dear ANURAG SINGH, refund of Rs. 40,000 against your Investment in Balanced+ Portfolio has been initiated. It may take 5-7 working days for same to get processed. - ETMONEY",
            expect = Expect(false, notes = "Refund initiated status is not bank credit."),
        ),
        Case(
            id = "ignore-mandate-registered-095",
            sender = "VM-AXISBK",
            body = "E-mandate for Rs 5,000.00 has been registered successfully for GROWW PAY SERVICES in A/c XX8291.",
            expect = Expect(false, notes = "Mandate registration is setup only."),
        ),
        Case(
            id = "ignore-standing-instruction-set-096",
            sender = "VM-HDFCBK",
            body = "Standing instruction has been set for Rs 2,000.00 towards mutual fund SIP from A/c XX1234.",
            expect = Expect(false, notes = "Standing instruction setup is not debit."),
        ),
        Case(
            id = "ignore-minimum-due-097",
            sender = "AD-ICICIT",
            body = "Minimum amount due Rs 2,450.00 on your ICICI Bank Credit Card XX1014. Due date is 12-Aug-26.",
            expect = Expect(false, notes = "Minimum due reminder is ignored."),
        ),
        Case(
            id = "ignore-offer-discount-098",
            sender = "VM-MYNTRA",
            body = "Flat 40% off plus coupon worth Rs 500 on Myntra. Shop now. T&C apply.",
            expect = Expect(false, notes = "Shopping promo is not a transaction."),
        ),
        Case(
            id = "ignore-neft-processing-099",
            sender = "VM-HDFCBK",
            body = "Your NEFT request of Rs 20,000.00 has been accepted and is under processing. Ref HDFC123456.",
            expect = Expect(false, notes = "Processing status is not completed movement."),
        ),
        Case(
            id = "ignore-delivery-alert-100",
            sender = "AD-AMAZON",
            body = "Your Amazon order worth Rs 1,299.00 has been delivered. Thank you for shopping with us.",
            expect = Expect(false, notes = "Order delivery notice is not ledger."),
        ),
        Case(
            id = "ignore-overdraft-sanctioned-101",
            sender = "VM-IDFCBK",
            body = "Overdraft facility has been sanctioned for Rs 1,00,000 on your IDFC FIRST Bank account. Use it anytime.",
            expect = Expect(false, notes = "Credit facility sanction is not movement."),
        ),
        Case(
            id = "ignore-card-limit-available-102",
            sender = "AD-HDFCBK",
            body = "Available credit limit on your HDFC Bank Credit Card XX1234 is Rs 2,26,151.86 as of 09-Aug-26.",
            expect = Expect(false, notes = "Available limit is balance info only."),
        ),
        Case(
            id = "ignore-upi-autopay-enabled-103",
            sender = "VM-NPCIUPI",
            body = "UPI AutoPay mandate for NETFLIX amount Rs 649.00 is enabled successfully. Next debit as per schedule.",
            expect = Expect(false, notes = "UPI AutoPay setup is not the debit."),
        ),
        Case(
            id = "ignore-card-payment-posted-104",
            sender = "AD-ICICIT",
            body = "Dear Customer, payment of INR 8,000.00 towards your Credit Card XX1014 has been posted on 08-08-26. Avl limit Rs 42,000.00",
            expect = Expect(false, notes = "Card payment posted acknowledgement is ignored."),
        ),
        Case(
            id = "ignore-sip-allotment-105",
            sender = "VM-MOAMC",
            body = "Dear Investor, SIP Purchase of Rs 3,000.00 in Motilal Oswal Flexi Cap Fund has been processed for NAV 55.321.",
            expect = Expect(false, notes = "Fund-house SIP allotment duplicates bank debit."),
        ),
        Case(
            id = "ignore-nach-returned-hdfc-106",
            sender = "VM-HDFCBK",
            body = "ACH debit towards HDFC BANK LTD for INR 27,136.00 has been returned today due to insufficient balance.",
            expect = Expect(false, notes = "Returned ACH is not a successful EMI debit."),
        ),
        Case(
            id = "ignore-loan-apply-now-107",
            sender = "VM-AXISBK",
            body = "Exclusive offer: personal loan up to Rs 5,00,000 for Axis Bank customers. Apply now for instant approval.",
            expect = Expect(false, notes = "Loan marketing is ignored."),
        ),
        Case(
            id = "ignore-coupon-voucher-108",
            sender = "VM-ZOMATO",
            body = "Use coupon FOOD500 and get free Rs 500 voucher on your next Zomato order. Hurry!",
            expect = Expect(false, notes = "Coupon/voucher promo is ignored."),
        ),
        Case(
            id = "ignore-insurance-due-109",
            sender = "VM-LICIND",
            body = "Your insurance premium of Rs 12,340.00 is due on 15-Aug-26. Pay now to keep policy active.",
            expect = Expect(false, notes = "Premium due notice is not paid movement."),
        ),
        Case(
            id = "ignore-card-autodebit-reminder-110",
            sender = "AD-SBICRD",
            body = "Your SBI Card payment of Rs 11,200.00 will be auto-debited from your registered bank account on due date.",
            expect = Expect(false, notes = "Future auto-debit reminder is ignored."),
        ),

        // --- Extra public-template keep cases (SBI / cheque / cash / wallets) ---
        Case(
            id = "keep-sbi-transferred-upi-111",
            sender = "VM-SBIINB",
            body = "Rs.450.00 transferred from A/c XX1234 on 15-APR via UPI to BIGBASKET Ref 412839. Avl Bal Rs 8,200.00",
            expect = Expect(true, TransactionType.DEBIT, Categories.GROCERIES, "450.00", "BigBasket", true, "SBI uses transferred-from wording for UPI spends."),
        ),
        Case(
            id = "keep-cheque-cleared-credit-112",
            sender = "VM-HDFCBK",
            body = "Cheque No. 123456 for Rs.50,000.00 has been cleared in your A/c XX1234 on 06-08-26. Avl Bal Rs 1,20,000.00",
            expect = Expect(true, TransactionType.CREDIT, Categories.TRANSFER, "50000.00", null, false, "Cheque clear is a credit movement on the account."),
        ),
        Case(
            id = "keep-cash-deposit-113",
            sender = "VM-AXISBK",
            body = "Cash deposit of INR 10,000.00 in A/c XX8291 on 02-08-26. Avl Bal INR 30,000.00",
            expect = Expect(true, TransactionType.CREDIT, Categories.TRANSFER, "10000.00", null, false, "Cash deposit is a real credit; not income by default."),
        ),
        Case(
            id = "keep-gpay-paid-to-vpa-114",
            sender = "VM-HDFCBK",
            body = "Rs.299.00 paid to merchant@okicici via UPI. Avbl bal Rs.5000",
            expect = Expect(true, TransactionType.DEBIT, Categories.OTHERS, "299.00", null, true, "GPay-style paid-to VPA debit without named merchant."),
        ),
        Case(
            id = "keep-paytm-you-have-paid-115",
            sender = "VM-PAYTMB",
            body = "You have paid Rs 75.50 to store123@paytm on 04-Nov-25",
            expect = Expect(true, TransactionType.DEBIT, Categories.OTHERS, "75.50", null, true, "Paytm wallet/UPI paid wording."),
        ),
        Case(
            id = "keep-vpa-linked-amazon-116",
            sender = "VM-INDBNK",
            body = "Your VPA 9876543210@ybl linked to Indian Bank a/c no. XXXXXX1234 is debited for Rs.499.00 and credited to amazon@apl (UPI Ref no 105201221633).",
            expect = Expect(true, TransactionType.DEBIT, Categories.SHOPPING, "499.00", "Amazon", true, "VPA-linked bank debit to amazon@apl."),
        ),
        Case(
            id = "keep-interest-credit-117",
            sender = "VM-SBIINB",
            body = "Your A/c XX9876 credited with interest Rs 245.50 on 01-Jul-26. Avl Bal Rs 50,245.50",
            expect = Expect(true, TransactionType.CREDIT, Categories.TRANSFER, "245.50", null, false, "Interest credit is money in; Transfer/Other income policy TBD."),
        ),
        Case(
            id = "ignore-upi-collect-request-118",
            sender = "VM-AXISBK",
            body = "UPI collect request of Rs 500.00 from merchant@okaxis. Approve in your UPI app.",
            expect = Expect(false, notes = "Collect request is not a completed debit."),
        ),
        Case(
            id = "ignore-emi-converted-ack-119",
            sender = "AX-ICICIB",
            body = "Your transaction of Rs 8,646.47 at Avenue Supermar on Card XX1014 has been converted to EMI. EMI of Rs 864 starts from 05-Aug-26.",
            expect = Expect(false, notes = "EMI conversion ack duplicates original card spend; do not re-book."),
        ),
        Case(
            id = "keep-phonepe-upi-120",
            sender = "VM-PHONPE",
            body = "Rs 150.00 debited from account ending 1234 to 9876543210@ybl on 04-11-25. UPI Ref: 432198765",
            expect = Expect(true, TransactionType.DEBIT, Categories.OTHERS, "150.00", null, true, "PhonePe UPI debit to VPA."),
        ),
    )
}
